"""
AI Helper for generating PR descriptions and commit messages
Uses Ollama or other local AI models for content generation
"""
import asyncio
import aiohttp
from typing import Dict, List, Optional
import os

class AIHelper:
    """
    AI-powered helper for generating PR descriptions and commit messages
    """
    
    def __init__(self):
        self.ollama_url = os.getenv("OLLAMA_URL", "http://localhost:11434")
        self.model = os.getenv("OLLAMA_MODEL", "llama3.2:3b")  # Default to a lightweight model
        self.timeout = 5  # seconds (OPTIMIZED: was 30s, now 5s for faster response)
        
    async def generate_pr_description(
        self,
        action_name: str,
        current_version: str,
        latest_version: str,
        org_name: str = None
    ) -> str:
        """
        Generate a PR description using AI for updating a GitHub Action.
        OPTIMIZED: Fast fallback with background AI processing
        """
        try:
            prompt = self._build_pr_prompt(action_name, current_version, latest_version, org_name)
            
            # PERFORMANCE OPTIMIZATION: Try AI with fast timeout, immediate fallback
            ai_task = asyncio.create_task(self._call_ollama(prompt))
            
            try:
                # Wait only 5 seconds for AI response
                ai_description = await asyncio.wait_for(ai_task, timeout=5.0)
                if ai_description:
                    print("✅ AI generated PR description in <5s")
                    return ai_description
            except asyncio.TimeoutError:
                print("⏱️ AI timeout after 5s, using fallback (background task continues)")
                # Cancel the AI task to free resources
                ai_task.cancel()
            
            # Immediate fallback - don't wait for AI
            return self._generate_fallback_description(action_name, current_version, latest_version)
                
        except Exception as e:
            print(f"AI description generation failed: {str(e)}")
            return self._generate_fallback_description(action_name, current_version, latest_version)
    
    async def generate_bulk_pr_description(
        self,
        actions: List[Dict[str, str]],
        org_name: str = None
    ) -> str:
        """
        Generate a PR description for bulk action updates.
        OPTIMIZED: Fast fallback with background AI processing
        """
        try:
            prompt = self._build_bulk_pr_prompt(actions, org_name)
            
            # PERFORMANCE OPTIMIZATION: Try AI with fast timeout, immediate fallback
            ai_task = asyncio.create_task(self._call_ollama(prompt))
            
            try:
                # Wait only 5 seconds for AI response
                ai_description = await asyncio.wait_for(ai_task, timeout=5.0)
                if ai_description:
                    print("✅ AI generated bulk PR description in <5s")
                    return ai_description
            except asyncio.TimeoutError:
                print("⏱️ AI timeout after 5s, using fallback (background task continues)")
                # Cancel the AI task to free resources
                ai_task.cancel()
            
            # Immediate fallback - don't wait for AI
            return self._generate_fallback_bulk_description(actions)
                
        except Exception as e:
            print(f"AI bulk description generation failed: {str(e)}")
            return self._generate_fallback_bulk_description(actions)
    
    def _build_pr_prompt(self, action_name: str, current_version: str, latest_version: str, org_name: str = None) -> str:
        """
        Build a prompt for AI to generate PR description.
        """
        return f"""You are a DevSecOps engineer writing a pull request description. 

Generate a clear, professional PR description for updating a GitHub Action. Use markdown formatting and include appropriate emojis.

Details:
- Action: {action_name}
- Current version: {current_version}
- Latest version: {latest_version}
- Organization: {org_name or 'N/A'}

Requirements:
- Start with a clear title using an emoji
- Explain what the update does
- List benefits of the update (security, bug fixes, features)
- Include a testing checklist
- Keep it concise but informative
- Use professional tone
- Add a footer noting it was auto-generated by devSecOps 

Format as markdown. Keep it under 100 words."""

    def _build_bulk_pr_prompt(self, actions: List[Dict[str, str]], org_name: str = None) -> str:
        """
        Build a prompt for AI to generate bulk PR description.
        """
        actions_list = "\n".join([
            f"- {action['action_name']}: {action['current_version']} → {action['latest_version']}"
            for action in actions
        ])
        
        return f"""You are a DevSecOps engineer writing a pull request description for a bulk update.

Generate a clear, professional PR description for updating multiple GitHub Actions at once. Use markdown formatting and include appropriate emojis.

Details:
- Number of actions: {len(actions)}
- Organization: {org_name or 'N/A'}
- Actions being updated:
{actions_list}

Requirements:
- Start with a clear title using an emoji
- Explain this is a bulk update
- List general benefits (security, performance, features)
- Include a comprehensive testing checklist
- Keep it concise but informative
- Use professional tone
- Add a footer noting it was auto-generated by devSecOps

Format as markdown. Keep it under 200 words."""

    async def _call_ollama(self, prompt: str) -> Optional[str]:
        """
        Call Ollama API to generate content.
        """
        try:
            async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=self.timeout)) as session:
                payload = {
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.7,
                        "top_p": 0.9,
                        "max_tokens": 500
                    }
                }
                
                async with session.post(
                    f"{self.ollama_url}/api/generate",
                    json=payload,
                    headers={"Content-Type": "application/json"}
                ) as response:
                    if response.status == 200:
                        result = await response.json()
                        return result.get("response", "").strip()
                    else:
                        print(f"Ollama API error: {response.status}")
                        return None
                        
        except asyncio.TimeoutError:
            print("Ollama API timeout")
            return None
        except aiohttp.ClientError as e:
            print(f"Ollama API connection error: {str(e)}")
            return None
        except Exception as e:
            print(f"Ollama API error: {str(e)}")
            return None
    
    def _generate_fallback_description(self, action_name: str, current_version: str, latest_version: str) -> str:
        """
        Generate a fallback PR description when AI is not available.
        """
        return f"""## 🔧 Update {action_name}

This PR updates the GitHub Action `{action_name}` from version `{current_version}` to `{latest_version}`.

### Changes
- ⬆️ Updated `{action_name}` to latest version `{latest_version}`
- 🔒 Ensures security updates and bug fixes are applied
- 📦 Maintains compatibility with existing workflow

## Benefits
- 🛡️ Security improvements
- 🐛 Bug fixes from recent releases
- 🚀 Performance enhancements
- 📋 Latest features and capabilities

### Testing
- [ ] Verify workflow still functions correctly
- [ ] Check for any breaking changes in the action
- [ ] Ensure all existing functionality is preserved
- [ ] Test the workflow end-to-end

---
*This PR was automatically generated by WithOps DevSecOps Platform*"""

    def _generate_fallback_bulk_description(self, actions: List[Dict[str, str]]) -> str:
        """
        Generate a fallback PR description for bulk updates.
        """
        actions_list = "\n".join([
            f"- `{action['action_name']}`: {action['current_version']} → {action['latest_version']}"
            for action in actions
        ])
        
        return f"""## 🔧 Update {len(actions)} GitHub Actions

This PR updates multiple GitHub Actions to their latest versions for improved security and functionality.

### Updated Actions
{actions_list}

### Benefits
- 🛡️ Security improvements across all actions
- 🐛 Bug fixes from recent releases
- 🚀 Performance enhancements
- 📋 Access to latest features and capabilities

### Testing
- [ ] Verify workflow still functions correctly
- [ ] Check for any breaking changes in the actions
- [ ] Ensure all existing functionality is preserved
- [ ] Test the workflow with all updated actions
- [ ] Verify CI/CD pipeline continues to work

---
*This PR was automatically generated by WithOps DevSecOps Platform*"""

    async def is_available(self) -> bool:
        """
        Check if AI service (Ollama) is available.
        """
        try:
            async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=5)) as session:
                async with session.get(f"{self.ollama_url}/api/tags") as response:
                    return response.status == 200
        except Exception:
            return False

    async def get_available_models(self) -> List[str]:
        """
        Get list of available models from Ollama.
        """
        try:
            async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
                async with session.get(f"{self.ollama_url}/api/tags") as response:
                    if response.status == 200:
                        data = await response.json()
                        return [model["name"] for model in data.get("models", [])]
                    return []
        except Exception:
            return []
